---
title: "SPPB Primary & Secondary Analyses with Imputed Data"
author: "Bruce Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/bruce/Desktop/GHRC Yan Lab/Hearing impairment & PF 2023')
library(haven)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(broom)
library(mice)
library(ggmice)
library(miceadds)
library(multcomp)
library(sandwich)
library(broom.mixed)
library(geepack)
```

## Load imputed data

```{r load imputed data}
load('outputs/pooled_11_15_imputed/pooled_11_15_imputed__DATALIST.Rdata')
imp <- datlist
```

## Calculate the SPPB score

```{r sppb score calculation}
# calculate the SPPB score

imp <- lapply(imp, function(df) {
  
  gait_quartiles <- quantile(df$gait, probs = seq(0, 1, 0.25), na.rm = T)
  cstand_quartiles <- quantile(df$cstand, probs = seq(0, 1, 0.25), na.rm = T)
  
  df <- df %>%
    mutate(gaitScore = case_when(
      is.na(gait) ~ NA,
      gait <= gait_quartiles[["25%"]] ~ 1,
      gait > gait_quartiles[["25%"]] & gait <= gait_quartiles[["50%"]] ~ 2,
      gait > gait_quartiles[["50%"]] & gait <= gait_quartiles[["75%"]] ~ 3,
      gait > gait_quartiles[["75%"]] ~ 4,
      .default = NA
      )) %>%
    mutate(standScore = case_when(
      is.na(cstand) ~ NA,
      cstand <= cstand_quartiles[["25%"]] ~ 4,
      cstand > cstand_quartiles[["25%"]] & cstand <= cstand_quartiles[["50%"]] ~ 3,
      cstand > cstand_quartiles[["50%"]] & cstand <= cstand_quartiles[["75%"]] ~ 2,
      cstand > cstand_quartiles[["75%"]] ~ 1,
      .default = NA
      ))
  
  # sum up the 3 items
  
  df <- df %>%
      mutate(SPPB = rowSums(across(c(gaitScore, standScore, balance)))) %>%
      arrange(id)
    
})

# imp<- lapply(imp, function(df) {
#     df <- as.data.frame(df)
# })

imp[[1]] %>%
  ggplot(aes(x=factor(SPPB))) + geom_bar()
```

## Primary analysis

# Model fitting for primary analysis

```{r fitting with imputed datasets for primary analysis, warning=FALSE}
model_results <- list()

for (i in seq_along(imp)) {
  
  fit_formula <- formula(SPPB ~ hr + age + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))
  
  model_results[[i]] <- geeglm(data = imp[[i]], formula = fit_formula, id = id, corstr = "unstructured")
}

pool.hearFit <- pool(model_results)
pool.hearFit %>%
  tidy(conf.int = TRUE) %>%
  mutate(across(c(estimate, conf.low, conf.high), ~round(., 2)),
         p.value = round(p.value, 3)) %>%
  mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
  mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
  dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
  filter(term %in% c("hr1"))
```

## Secondary analyses

# Limit to 2 visits or above

```{r limit to 2 visits or above}

imp <- lapply(imp, function(df) {
  
    df <- df %>%
      arrange(id,wave) %>%
      group_by(id) %>%
      filter(n() >= 2) %>%
      ungroup() %>%
      mutate(centered_age = age - 60)
    
    df <- df %>%
      arrange(id)
    
})

```

# Fit with study visits

```{r study visits}
model_results2 <- list()

for (i in seq_along(imp)) {
  
  fit_formula <- formula(SPPB ~ hr*visit + age + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))
  
  model_results2[[i]] <- geeglm(data = imp[[i]], formula = fit_formula, id = id, corstr = "unstructured")
}

model_results3 <- list()

for(i in seq_along(imp)) {
    model_results3[[i]] <- glht(model_results2[[i]], linfct = c("visit + hr1:visit = 0"))
}
```

# Fit with years after 60

```{r years after 60}
model_results4 <- list()

for (i in seq_along(imp)) {
  
  fit_formula <- formula(SPPB ~ hr*centered_age + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))
  
  model_results4[[i]] <- geeglm(data = imp[[i]], formula = fit_formula, id = id, corstr = "unstructured")
}

model_results5 <- list()

for(i in seq_along(imp)) {
    model_results5[[i]] <- glht(model_results4[[i]], linfct = c("centered_age + hr1:centered_age = 0"))
}
```

# Pool study visit results

```{r pool secondary analysis with visit, warning=FALSE}
pool.hearFit2 <- pool(model_results2)
pool.hearFit2 %>%
  tidy(conf.int = TRUE) %>%
  mutate(across(c(estimate, conf.low, conf.high), ~round(., 3)),
         p.value = round(p.value, 3)) %>%
  mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
  mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
  dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
  filter(term %in% c("hr1", "visit", "hr1:visit"))

pool.hearFit3 <- pool(model_results3)
pool.hearFit3 %>%
  tidy(conf.int = TRUE) %>%
  mutate(across(c(estimate, conf.low, conf.high), ~round(., 2)),
         p.value = round(p.value, 3)) %>%
  mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
  dplyr::select(contrast,estimate,CI,p.value)
```

# Pool years after 60 results

```{r pool secondary analysis with years after 60, warning=FALSE}
pool.hearFit4 <- pool(model_results4)
pool.hearFit4 %>%
  tidy(conf.int = TRUE) %>%
  mutate(across(c(estimate, conf.low, conf.high), ~round(., 3)),
         p.value = round(p.value, 3)) %>%
  mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
  mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
  dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
  filter(term %in% c("hr1", "centered_age", "hr1:centered_age"))

pool.hearFit5 <- pool(model_results5)
pool.hearFit5 %>%
  tidy(conf.int = TRUE) %>%
  mutate(across(c(estimate, conf.low, conf.high), ~round(., 2)),
         p.value = round(p.value, 3)) %>%
  mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
  dplyr::select(contrast,estimate,CI,p.value)
```