---
title: "Subgroup analyses for age"
author: "Bruce Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/Users/bruce/Desktop/GHRC Yan Lab/Hearing impairment & PF 2023')
rm(list = ls())
library(haven)
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(broom)
library(multcomp)
library(broom.mixed)
library(mice)
library(geepack)
library(multgee)
```

## Load data

```{r load data}
setwd("/Users/bruce/Desktop/GHRC Yan Lab/Hearing impairment & PF 2023")
load('outputs/pooled_11_15_imputed/pooled_11_15_imputed__DATALIST.Rdata')
```

## Calculate the SPPB score

```{r sppb calculation}
imp <- datlist
process_full_datlist <- function(df) {

  gait_quartiles <- quantile(df$gait, probs = seq(0, 1, 0.25), na.rm = T)
  cstand_quartiles <- quantile(df$cstand, probs = seq(0, 1, 0.25), na.rm = T)
  
  df <- df %>%
    mutate(gaitScore = case_when(
      is.na(gait) ~ NA,
      gait <= gait_quartiles[["25%"]] ~ 1,
      gait > gait_quartiles[["25%"]] & gait <= gait_quartiles[["50%"]] ~ 2,
      gait > gait_quartiles[["50%"]] & gait <= gait_quartiles[["75%"]] ~ 3,
      gait > gait_quartiles[["75%"]] ~ 4,
      .default = NA
      )) %>%
    mutate(standScore = case_when(
      is.na(cstand) ~ NA,
      cstand <= cstand_quartiles[["25%"]] ~ 4,
      cstand > cstand_quartiles[["25%"]] & cstand <= cstand_quartiles[["50%"]] ~ 3,
      cstand > cstand_quartiles[["50%"]] & cstand <= cstand_quartiles[["75%"]] ~ 2,
      cstand > cstand_quartiles[["75%"]] ~ 1,
      .default = NA
      ))
  
  # sum up the 3 items
  
  df <- df %>%
      mutate(SPPB = rowSums(across(c(gaitScore, standScore, balance)))) %>%
      arrange(id)
  
  # create age groups
  df <- df %>%
    arrange(id, wave) %>%
    group_by(id) %>%
    mutate(age_group = cut(min(age), breaks = c(60, 69, 79, 115), right = TRUE, include.lowest = TRUE, labels = FALSE)) %>%
    mutate(age_group = age_group - 1) %>%
    mutate(age_group = factor(age_group)) %>%
    ungroup()

}

process_age_group <- function(df, age_min, age_max) {
  
  df <- df %>%
    arrange(id, wave) %>%
    group_by(id) %>%
    filter(age[1] >= age_min & age[1] <= age_max) %>%
    ungroup()

  gait_quartiles <- quantile(df$gait, probs = seq(0, 1, 0.25), na.rm = T)
  cstand_quartiles <- quantile(df$cstand, probs = seq(0, 1, 0.25), na.rm = T)
  
  df <- df %>%
    mutate(gaitScore = case_when(
      is.na(gait) ~ NA,
      gait <= gait_quartiles[["25%"]] ~ 1,
      gait > gait_quartiles[["25%"]] & gait <= gait_quartiles[["50%"]] ~ 2,
      gait > gait_quartiles[["50%"]] & gait <= gait_quartiles[["75%"]] ~ 3,
      gait > gait_quartiles[["75%"]] ~ 4,
      .default = NA
      )) %>%
    mutate(standScore = case_when(
      is.na(cstand) ~ NA,
      cstand <= cstand_quartiles[["25%"]] ~ 4,
      cstand > cstand_quartiles[["25%"]] & cstand <= cstand_quartiles[["50%"]] ~ 3,
      cstand > cstand_quartiles[["50%"]] & cstand <= cstand_quartiles[["75%"]] ~ 2,
      cstand > cstand_quartiles[["75%"]] ~ 1,
      .default = NA
      ))
  
  # sum up the 3 items
  
  df <- df %>%
      mutate(SPPB = rowSums(across(c(gaitScore, standScore, balance)))) %>%
      arrange(id)

}

# Apply the function to generate each age group
imp60_69 <- lapply(datlist, process_age_group, age_min = 60, age_max = 69)
imp70_79 <- lapply(datlist, process_age_group, age_min = 70, age_max = 79)
imp80 <- lapply(datlist, process_age_group, age_min = 80, age_max = Inf)
imp <- lapply(datlist, process_full_datlist)

# Determine the number of participants
length(unique(imp60_69[[1]]$id))
length(unique(imp70_79[[1]]$id))
length(unique(imp80[[1]]$id))
length(unique(imp[[1]]$id))
```

## Define model formulas

```{r model formulas}
fit_formula_sppb <- formula(SPPB ~ hr + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_gait <- formula(gait ~ hr + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_cstand <- formula(log(cstand) ~ hr + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_balance <- formula(balance ~ hr + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_sppb_interaction <- formula(SPPB ~ hr*age_group + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_gait_interaction <- formula(gait ~ hr*age_group + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_cstand_interaction <- formula(log(cstand) ~ hr*age_group + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))

fit_formula_balance_interaction <- formula(balance ~ hr*age_group + sex + residence + as.factor(education) + marital + as.factor(hhconsumpLevel) + as.factor(mbmi) + smoke + drink + hibpe + diabe + cancer + lunge + hearte + stroke + arthre + dyslipe + livere + kidneye + asthmae + as.factor(wave))
```

## Define function for pooling results

```{r}
pool_estimates <- function(model_results, exponentiate = F) {
  
  if (exponentiate == FALSE) {
    pool.fit <- pool(model_results)
    pool.fit %>%
    tidy(conf.int = TRUE) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~round(., 3)),
           p.value = round(p.value, 3)) %>%
    mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
    mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
    dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
    filter(term %in% c("hr1"))
  } else {
    pool.fit <- pool(model_results)
    pool.fit %>%
    tidy(conf.int = TRUE) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~round(exp(.), 3)),
           p.value = round(p.value, 3)) %>%
    mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
    mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
    dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
    filter(term %in% c("hr1"))
  }
}

pool_balance <- function(model_results) {
  
  param_results <- c()
  vcov_results <- c()
  
  for (i in seq_along(model_results)) {
    param_results <- c(param_results, coef(model_results[[i]])[["hr1"]])
    vcov_results <- c(vcov_results, vcov(model_results[[i]])["hr1","hr1"])
  }

  pooled_results <- pool.scalar(param_results, vcov_results)

  beta_hat <- pooled_results$qbar
  se <- sqrt(pooled_results$ubar)
  p_value <- 1 - pt(beta_hat / se, df = pooled_results$df)
  ci <- round(exp(beta_hat + c(-1,1) * 1.96 * se), 2)
  
  return(tibble(estimate = round(exp(beta_hat), 2), lower = ci[1], upper = ci[2], p_value = p_value))
}
```


## 60 - 69 age group

```{r}
sppb <- list()

for (i in seq_along(imp60_69)) {
  sppb[[i]] <- geeglm(data = imp60_69[[i]], formula = fit_formula_sppb, id = id, corstr = "independence")
}

gait <- list()

for (i in seq_along(imp60_69)) {
  gait[[i]] <- geeglm(data = imp60_69[[i]], formula = fit_formula_gait, id = id, corstr = "unstructured")
}

cstand <- list()

for (i in seq_along(imp60_69)) {
  cstand[[i]] <- geeglm(data = imp60_69[[i]], formula = fit_formula_cstand, id = id, corstr = "unstructured")
}

balance <- list()

for (i in seq_along(imp60_69)) {
  balance[[i]] <- ordLORgee(data = imp60_69[[i]], formula = fit_formula_balance, id = id, LORstr = "uniform")
}

# pool the results
pool_estimates(sppb)
pool_estimates(gait)
pool_estimates(cstand, exponentiate = TRUE)
pool_balance(balance)
```

## 70 - 79 age group

```{r}
sppb <- list()

for (i in seq_along(imp70_79)) {
  sppb[[i]] <- geeglm(data = imp70_79[[i]], formula = fit_formula_sppb, id = id, corstr = "independence")
}

gait <- list()

for (i in seq_along(imp70_79)) {
  gait[[i]] <- geeglm(data = imp70_79[[i]], formula = fit_formula_gait, id = id, corstr = "unstructured")
}

cstand <- list()

for (i in seq_along(imp70_79)) {
  cstand[[i]] <- geeglm(data = imp70_79[[i]], formula = fit_formula_cstand, id = id, corstr = "unstructured")
}

balance <- list()

for (i in seq_along(imp70_79)) {
  balance[[i]] <- ordLORgee(data = imp70_79[[i]], formula = fit_formula_balance, id = id, LORstr = "uniform")
}

# pool the results
pool_estimates(sppb)
pool_estimates(gait)
pool_estimates(cstand, exponentiate = TRUE)
pool_balance(balance)
```

## 80+ age group

```{r}
sppb <- list()

for (i in seq_along(imp80)) {
  sppb[[i]] <- geeglm(data = imp80[[i]], formula = fit_formula_sppb, id = id, corstr = "independence")
}

gait <- list()

for (i in seq_along(imp80)) {
  gait[[i]] <- geeglm(data = imp80[[i]], formula = fit_formula_gait, id = id, corstr = "unstructured")
}

cstand <- list()

for (i in seq_along(imp80)) {
  cstand[[i]] <- geeglm(data = imp80[[i]], formula = fit_formula_cstand, id = id, corstr = "unstructured")
}

balance <- list()

for (i in seq_along(imp80)) {
  balance[[i]] <- ordLORgee(data = imp80[[i]], formula = fit_formula_balance, id = id, LORstr = "uniform")
}

# pool the results
pool_estimates(sppb)
pool_estimates(gait)
pool_estimates(cstand, exponentiate = TRUE)
pool_balance(balance)
```

## p-interactions


```{r}
pool_estimates <- function(model_results, exponentiate = F) {
  
  if (exponentiate == FALSE) {
    pool.fit <- pool(model_results)
    pool.fit %>%
    tidy(conf.int = TRUE) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~round(., 3)),
           p.value = round(p.value, 3)) %>%
    mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
    mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
    dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
    filter(term %in% c("hr1:age_group1", "hr1:age_group2"))
  } else {
    pool.fit <- pool(model_results)
    pool.fit %>%
    tidy(conf.int = TRUE) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~round(exp(.), 3)),
           p.value = round(p.value, 3)) %>%
    mutate(CI = paste0(conf.low ,", ", conf.high)) %>%
    mutate(beta_CI = paste0(estimate, " (", CI, ")")) %>%
    dplyr::select(c(term, estimate, p.value, CI, beta_CI)) %>%
    filter(term %in% c("hr1:age_group1", "hr1:age_group2"))
  }
}

pool_balance <- function(model_results, coef = "hr1") {
  
  param_results <- c()
  vcov_results <- c()
  
  for (i in seq_along(model_results)) {
    param_results <- c(param_results, coef(model_results[[i]])[[coef]])
    vcov_results <- c(vcov_results, vcov(model_results[[i]])[coef, coef])
  }

  pooled_results <- pool.scalar(param_results, vcov_results)

  beta_hat <- pooled_results$qbar
  se <- sqrt(pooled_results$ubar)
  p_value <- 1 - pt(beta_hat / se, df = pooled_results$df)
  ci <- round(exp(beta_hat + c(-1,1) * 1.96 * se), 2)
  
  return(tibble(estimate = round(exp(beta_hat), 2), lower = ci[1], upper = ci[2], p_value = p_value))
}
```


```{r}
sppb <- list()

for (i in seq_along(imp)) {
  sppb[[i]] <- geeglm(data = imp[[i]], formula = fit_formula_sppb_interaction, id = id, corstr = "independence")
}

gait <- list()

for (i in seq_along(imp)) {
  gait[[i]] <- geeglm(data = imp[[i]], formula = fit_formula_gait_interaction, id = id, corstr = "unstructured")
}

cstand <- list()

for (i in seq_along(imp)) {
  cstand[[i]] <- geeglm(data = imp[[i]], formula = fit_formula_cstand_interaction, id = id, corstr = "unstructured")
}

balance <- list()

for (i in seq_along(imp)) {
  balance[[i]] <- ordLORgee(data = imp[[i]], formula = fit_formula_balance_interaction, id = id, LORstr = "uniform")
}

# pool the results
pool_estimates(sppb)
pool_estimates(gait)
pool_estimates(cstand, exponentiate = TRUE)
pool_balance(balance, "hr1:age_group1")
pool_balance(balance, "hr1:age_group2")
```

